name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Ensure the correct folder is checked out for your content
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: JordanFrecon/jupyterlite
          path: content

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Build JupyterLite site with content folder
      - name: Build JupyterLite site
        run: |
          jupyter lite build --contents ./content

      - name: Upload built site (dist)
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite-build
          path: ./_build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jupyterlite-build
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          branch: gh-pages
